### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [paladin3895/google-search#2]
Hello Dat 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days. As a result, ensure you are responsive during this process. If you need additional time, please inform us immediately so we can plan accordingly.

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by paladin3895** [comment]
Hi Olivier,
Thank you for taking time to review and suggest improvements for my code, much appreciated.
However, please note that I'm out on a family trip and will return tomorrow so I'll start create Pull Request from tomorrow afternoon. Hopefully you're OK with this.
Kind regards,

**Comment by olivierobert** [comment]
Fixes are welcome, and above all we would like to hear your feedback on all open issues :-)

**Comment by olivierobert** [comment]
I have now completed the first round of reviews. Looking forward to hearing from you on the open issues.

**Comment by paladin3895** [comment]
Hi @olivierobert ,
I have opened several pull requests to fix/improve the issues, please have a look when you have time.
I will update demo server once we merge the pull requests.
Regards,

**Comment by olivierobert** [comment]
I have reviewed the pull requests and added some comments. 

The changes for the scraper were good. You could see the need to add tests required to make architectural changes 💪 That's why testing is needed.

We appreciate your efforts on the code challenge. It is now time to wrap up this stage of the recruitment process. Our Talent team will share with you the next steps. Please allow a longer period for our team to responds due to the Tet holidays.

Thank you!
